services:
  postgres:
    image: postgres:15
    container_name: pet-postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "6700:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "6703:6703"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:6703
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:6703
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  storage-service:
    build:
      context: .
      dockerfile: ./storage/Dockerfile
    depends_on:
      - postgres
    ports:
      - "6701:6701"
  api-service:
    build:
      context: .
      dockerfile: api-service-2/Dockerfile
    depends_on:
      - storage-service
      - kafka
    ports:
      - "6702:6702"
  kafka-service:
    build:
      context: .
      dockerfile: kafka/Dockerfile
    depends_on:
      - kafka
    ports:
      - "6704:6704"
volumes:
  pgdata: